[toolchain]
anchor_version = "0.29.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
kamino_deposit = "HcxtR55Ec4XQPt47SckxG6RMoWyFAEbSYn5BTmVX7DEE"

[programs.devnet]
kamino_deposit = "HcxtR55Ec4XQPt47SckxG6RMoWyFAEbSYn5BTmVX7DEE"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "Devnet"
wallet = "/home/averek/.config/solana/id.json"

[test]
startup_wait = 20000

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
